import json
import os
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import reload_displays as target


SAMPLE = '''-- Generated by hyprmoncfg
hl.monitor({
  output = "DP-1",
  mode = "1920x1080@60",
})
hl.monitor({
  output = "HDMI-A-2",
  mode = "1920x1080@60",
})
hl.workspace_rule({ workspace = "1", monitor = "DP-1" })
'''


class ConfigurationTests(unittest.TestCase):
    def test_only_selected_block_is_disabled(self):
        changed = target.temporary_configuration(SAMPLE, {"HDMI-A-2"})
        self.assertEqual(changed.count("disabled = true,"), 1)
        self.assertIn('output = "HDMI-A-2",\n  disabled = true,', changed)
        self.assertEqual(SAMPLE.split("hl.monitor({")[1], changed.split("hl.monitor({")[1])
        self.assertTrue(changed.endswith('hl.workspace_rule({ workspace = "1", monitor = "DP-1" })\n'))

    def test_missing_output_is_rejected(self):
        with self.assertRaisesRegex(ValueError, "找不到输出"):
            target.temporary_configuration(SAMPLE, {"DP-9"})

    def test_failure_during_first_reload_restores_config_and_service(self):
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            config = base / "config" / "hypr" / "hyprmoncfg-monitors.lua"
            config.parent.mkdir(parents=True)
            config.write_text(SAMPLE, encoding="utf-8")
            runtime = base / "runtime"
            runtime.mkdir()
            calls = []
            reloads = 0

            def command(*args):
                nonlocal reloads
                calls.append(args)
                if args == ("hyprctl", "monitors", "-j"):
                    return json.dumps([{"name": "HDMI-A-2", "disabled": False}])
                if args == ("hyprctl", "reload"):
                    reloads += 1
                    if reloads == 1:
                        self.assertIn("disabled = true,", config.read_text())
                        raise RuntimeError("模拟首次重载失败")
                return ""

            environment = {"XDG_CONFIG_HOME": str(base / "config"), "XDG_RUNTIME_DIR": str(runtime)}
            with patch.dict(os.environ, environment), patch.object(target, "command", side_effect=command), \
                 patch.object(target.time, "sleep"):
                with self.assertRaisesRegex(RuntimeError, "模拟首次重载失败"):
                    target.reload_displays({"HDMI-A-2"})

            self.assertEqual(config.read_text(), SAMPLE)
            self.assertEqual(reloads, 2)
            self.assertIn(("systemctl", "--user", "start", "hyprmoncfgd.service"), calls)
            self.assertEqual(list(runtime.glob("*.lua")), [])


if __name__ == "__main__":
    unittest.main()
