import json
import os
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import reload_displays as target


SAMPLE = '''-- Generated by hyprmoncfg
hl.monitor({
  output = "DP-1",
  mode = "1920x1080@60",
})
hl.monitor({
  output = "HDMI-A-2",
  mode = "1920x1080@60",
})
hl.workspace_rule({ workspace = "1", monitor = "DP-1" })
'''


class ConfigurationTests(unittest.TestCase):
    def test_only_selected_block_is_disabled(self):
        changed = target.temporary_configuration(SAMPLE, {"HDMI-A-2"})
        self.assertEqual(changed.count("disabled = true,"), 1)
        self.assertIn('output = "HDMI-A-2",\n  disabled = true,', changed)
        self.assertEqual(SAMPLE.split("hl.monitor({")[1], changed.split("hl.monitor({")[1])
        self.assertTrue(changed.endswith('hl.workspace_rule({ workspace = "1", monitor = "DP-1" })\n'))

    def test_missing_output_is_rejected(self):
        with self.assertRaisesRegex(ValueError, "找不到输出"):
            target.temporary_configuration(SAMPLE, {"DP-9"})

    def test_symlink_lock_does_not_truncate_its_target(self):
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            config = base / "config" / "hypr" / "hyprmoncfg-monitors.lua"
            config.parent.mkdir(parents=True)
            config.write_text(SAMPLE, encoding="utf-8")
            runtime = base / "runtime"
            runtime.mkdir()
            victim = base / "victim"
            victim.write_text("keep me", encoding="utf-8")
            (runtime / "andy-display-reset.lock").symlink_to(victim)
            calls = []

            def command(*args):
                calls.append(args)
                if args == ("hyprctl", "monitors", "-j"):
                    return json.dumps([{"name": "HDMI-A-2", "disabled": False}])
                return ""

            environment = {"XDG_CONFIG_HOME": str(base / "config"), "XDG_RUNTIME_DIR": str(runtime)}
            with patch.dict(os.environ, environment), patch.object(target, "command", side_effect=command):
                with self.assertRaises(OSError):
                    target.reload_displays({"HDMI-A-2"})

            self.assertEqual(victim.read_text(encoding="utf-8"), "keep me")
            self.assertEqual(config.read_text(encoding="utf-8"), SAMPLE)
            self.assertNotIn(("systemctl", "--user", "stop", "hyprmoncfgd.service"), calls)

    def test_existing_regular_lock_is_not_truncated(self):
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            config = base / "config" / "hypr" / "hyprmoncfg-monitors.lua"
            config.parent.mkdir(parents=True)
            config.write_text(SAMPLE, encoding="utf-8")
            runtime = base / "runtime"
            runtime.mkdir()
            lock = runtime / "andy-display-reset.lock"
            lock.write_text("existing lock contents", encoding="utf-8")

            def command(*args):
                if args == ("hyprctl", "monitors", "-j"):
                    return json.dumps([{"name": "HDMI-A-2", "disabled": False}])
                return ""

            environment = {"XDG_CONFIG_HOME": str(base / "config"), "XDG_RUNTIME_DIR": str(runtime)}
            with patch.dict(os.environ, environment), patch.object(target, "command", side_effect=command), \
                 patch.object(target.time, "sleep"):
                self.assertIn("HDMI-A-2", target.reload_displays({"HDMI-A-2"}))

            self.assertEqual(lock.read_text(encoding="utf-8"), "existing lock contents")
            self.assertEqual(config.read_text(encoding="utf-8"), SAMPLE)

    def test_nonregular_lock_is_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            lock = Path(directory) / "andy-display-reset.lock"
            os.mkfifo(lock)
            with self.assertRaisesRegex(RuntimeError, "锁文件不是当前用户拥有的常规文件"):
                target.open_regular_lockfile(lock)

    def test_failure_during_first_reload_restores_config_and_service(self):
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            config = base / "config" / "hypr" / "hyprmoncfg-monitors.lua"
            config.parent.mkdir(parents=True)
            config.write_text(SAMPLE, encoding="utf-8")
            runtime = base / "runtime"
            runtime.mkdir()
            calls = []
            reloads = 0

            def command(*args):
                nonlocal reloads
                calls.append(args)
                if args == ("hyprctl", "monitors", "-j"):
                    return json.dumps([{"name": "HDMI-A-2", "disabled": False}])
                if args == ("hyprctl", "reload"):
                    reloads += 1
                    if reloads == 1:
                        self.assertIn("disabled = true,", config.read_text())
                        raise RuntimeError("模拟首次重载失败")
                return ""

            environment = {"XDG_CONFIG_HOME": str(base / "config"), "XDG_RUNTIME_DIR": str(runtime)}
            with patch.dict(os.environ, environment), patch.object(target, "command", side_effect=command), \
                 patch.object(target.time, "sleep"):
                with self.assertRaisesRegex(RuntimeError, "模拟首次重载失败"):
                    target.reload_displays({"HDMI-A-2"})

            self.assertEqual(config.read_text(), SAMPLE)
            self.assertEqual(reloads, 2)
            self.assertIn(("systemctl", "--user", "start", "hyprmoncfgd.service"), calls)
            self.assertEqual(list(runtime.glob("*.lua")), [])

    def test_interrupt_during_service_stop_still_starts_service(self):
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            config = base / "config" / "hypr" / "hyprmoncfg-monitors.lua"
            config.parent.mkdir(parents=True)
            config.write_text(SAMPLE, encoding="utf-8")
            runtime = base / "runtime"
            runtime.mkdir()
            calls = []

            def command(*args):
                calls.append(args)
                if args == ("hyprctl", "monitors", "-j"):
                    return json.dumps([{"name": "HDMI-A-2", "disabled": False}])
                if args == ("systemctl", "--user", "stop", "hyprmoncfgd.service"):
                    raise InterruptedError("模拟停止服务时中断")
                return ""

            environment = {"XDG_CONFIG_HOME": str(base / "config"), "XDG_RUNTIME_DIR": str(runtime)}
            with patch.dict(os.environ, environment), patch.object(target, "command", side_effect=command):
                with self.assertRaisesRegex(RuntimeError, "模拟停止服务时中断"):
                    target.reload_displays({"HDMI-A-2"})

            self.assertEqual(config.read_text(), SAMPLE)
            self.assertIn(("systemctl", "--user", "start", "hyprmoncfgd.service"), calls)

    def test_concurrent_config_change_is_preserved_and_backup_is_retained(self):
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            config = base / "config" / "hypr" / "hyprmoncfg-monitors.lua"
            config.parent.mkdir(parents=True)
            config.write_text(SAMPLE, encoding="utf-8")
            runtime = base / "runtime"
            runtime.mkdir()
            calls = []
            external_change = SAMPLE + "-- edited while reloading\n"

            def command(*args):
                calls.append(args)
                if args == ("hyprctl", "monitors", "-j"):
                    return json.dumps([{"name": "HDMI-A-2", "disabled": False}])
                return ""

            environment = {"XDG_CONFIG_HOME": str(base / "config"), "XDG_RUNTIME_DIR": str(runtime)}
            with patch.dict(os.environ, environment), patch.object(target, "command", side_effect=command), \
                 patch.object(target.time, "sleep", side_effect=lambda _: config.write_text(external_change)):
                with self.assertRaisesRegex(RuntimeError, "配置文件在重载期间已被修改，未覆盖"):
                    target.reload_displays({"HDMI-A-2"})

            self.assertEqual(config.read_text(), external_change)
            backups = list(runtime.glob("*.lua"))
            self.assertEqual(len(backups), 1)
            self.assertEqual(backups[0].read_text(), SAMPLE)
            self.assertEqual(calls.count(("hyprctl", "reload")), 2)
            self.assertIn(("systemctl", "--user", "start", "hyprmoncfgd.service"), calls)

    def test_interrupt_after_temporary_replace_restores_config(self):
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            config = base / "config" / "hypr" / "hyprmoncfg-monitors.lua"
            config.parent.mkdir(parents=True)
            config.write_text(SAMPLE, encoding="utf-8")
            runtime = base / "runtime"
            runtime.mkdir()
            calls = []
            original_write = target.write_atomically
            writes = 0

            def command(*args):
                calls.append(args)
                if args == ("hyprctl", "monitors", "-j"):
                    return json.dumps([{"name": "HDMI-A-2", "disabled": False}])
                return ""

            def write_then_interrupt(*args):
                nonlocal writes
                writes += 1
                original_write(*args)
                if writes == 1:
                    raise InterruptedError("模拟写入后中断")

            environment = {"XDG_CONFIG_HOME": str(base / "config"), "XDG_RUNTIME_DIR": str(runtime)}
            with patch.dict(os.environ, environment), patch.object(target, "command", side_effect=command), \
                 patch.object(target, "write_atomically", side_effect=write_then_interrupt):
                with self.assertRaisesRegex(RuntimeError, "模拟写入后中断"):
                    target.reload_displays({"HDMI-A-2"})

            self.assertEqual(config.read_text(), SAMPLE)
            self.assertEqual(writes, 2)
            self.assertEqual(list(runtime.glob("*.lua")), [])
            self.assertIn(("systemctl", "--user", "start", "hyprmoncfgd.service"), calls)


if __name__ == "__main__":
    unittest.main()
